name = "Portfolio Site"
homepage = "https://yxlow07.github.io/"
languageCode = "en-us"
title = "Yu Xuan's Portfolio"

[params]
  staticPath = ""
  staticImagePath = "/images"
  assetPath = ""
  favicon = "images/codeforces.png"
  blogPath = "/blog/"
  math = false
  [params.social]
    github = "https://github.com/yxlow07"
    linkedin = "https://linkedin.com/in/low-yu-xuan/"
    email = "yuxuanlow013@gmail.com"
    instagram = "https://www.instagram.com/_yu_xuan_07/"
  [params.contact]
    formAction = "https://formspree.io/f/mrbqlvkj"
  [params.contact.mentorship]
    title = "Coding Mentorship"
    description = "I offer mentorship for aspiring programmers, competitive or not. Whether you're just starting or looking to improve your skills, I can help guide your learning journey."
    buttonText = "Inquire about Mentorship"
    inquiryLink = "mailto:yuxuanlow013@gmail.com?subject=Mentorship%20Inquiry"

[permalinks]
  blog = "/blog/:filename/"

[taxonomies]
    tag = "tags"
    category = "categories"

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
tabWidth = 2
style = "onedark"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      tasklist = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/#about"
    weight = 10
  [[menu.main]]
    name = "Education"
    url = "/#education"
    weight = 20
  [[menu.main]]
    name = "Projects"
    url = "/#projects"
    weight = 30
  [[menu.main]]
    name = "Achievements"
    url = "/#achievements"
    weight = 40
  [[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 50
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 60